[project]
name = "mentor-bootcamp"
version = "0.1.0"
description = ""
authors = [
    {name = "Mart",email = "martinqwq4@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "mentor_bootcamp", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.4,<0.17.0)",
    "black (>=26.5.1,<27.0.0)"
]

# НАСТРОЙКА BLACK ДЛЯ УСТРАНЕНИЯ WARNING
[tool.black]
target-version = ['py312']